server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxx/databases?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    hikari:
      username: xxxx
      password: xxx
      max-lifetime: 60000


  jpa:
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: xxxxx
      port: xxxx
      password: xxxx
      database: 0
      connect-timeout: 10000

springdoc:
  swagger-ui:
    path: /doc/
  api-docs:
    path: /doc

security:
  permit-paths:
   - "/auth/login/code"
   - "/auth/login/password"
   - "/error"
   - "/sms"


headers:
  key: "xxxxx"
  value: "xxxxxxxxx"

gain:
  sms: "http://localhost:2000/"
  oss: "http://localhost:2001/"
