server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/databases?useUnicode=true&characterEncoding=utf-8&userSSL=true&serverTimezone=UTC
    hikari:
      username: root
      password: databases
      max-lifetime: 60000


  jpa:
    hibernate:
      ddl-auto: update


  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 10000

# openapi documents
springdoc:
  swagger-ui:
    path: /doc/
  api-docs:
    path: /doc


# 跳过验证的请求
security:
  permit-paths:
   - "/auth/login/code"
   - "/auth/login/password"
   - "/error"
   - "/sms"


# 自定义header
headers:
  key: "xxxxx"
  value: "xxxxxxxxx"


# 短信服务+oss
gain:
  sms: "http://localhost:2000/"
  oss: "http://localhost:2001/"
